apiVersion: v2
appVersion: "0.0.2"
version: 1.0.6
name: admission-controller
description: Lacework admission controller using Lacework proxy scanner
type: application
keywords:
- admission-controller
- runtime-security
- lacework
home: https://ChitraPKumar.github.io/admission-controller/
maintainers:
  - name: chitrapkumar
    email: chitra.kumar@lacework.net

