apiVersion: v2
appVersion: "0.0.2"
version: 2.1
name: admission-controller
description: Lacework admission controller using Lacework proxy scanner
type: application
keywords:
- admission-controller
- runtime-security
- lacework
maintainers:
  - name: chitrapkumar
    email: chitra.kumar@lacework.net

