name: helios

# Configuration
logger:
  debug: true

admission:
  tls_port: 8443
  cert_file_path: "/certs/helios.crt"
  cert_key_path: "/certs/helios.key"

certs:
  create: false # Set to false for existing certs
  name: helios-admission-certs # If you're using existing certs change the name to existing secret name
  serverCertificate:
  serverKey:
  caCert:

lacework:
  account:
  api_key:
  api_secret:

policy:
  block_exec: false
  bypass_scope: "kube-system,kube-public,lacework,lacework-dev"
  opa: false
  server:
  port: 8443

scanner:
  server: "proxy-scanner"
  namespace: "lacework-dev"
  port: "8080"
  path: "v1/scan"
  timeout: 30000

# Kubernetes
nameOverride: "helios"
fullnameOverride: "helios"

serviceAccount:
  name: helios-admission-sa

clusterRole:
  name: helios-admission

clusterRoleBinding:
  name: helios-admission

role:
  name: helios-admission

roleBinding:
  name: helios-admission

webhooks:
  caBundle:
  failurePolicy: Ignore
  validatingWebhook:
    name: helios-admission-hook-config

podAnnotations: {}
#  my-annotation-key: my value; more value

securityContext:
  runAsUser: 11431
  runAsGroup: 11433
  fsGroup: 11433
container_securityContext: {}

resources: {}
  # requests:
  #   cpu: 250m
  #   memory: 0.2Gi
  # limits:
  #   cpu: 500m
#   memory: 1.5Gi

nodeSelector: {}

deployment:
  image:
  tag:
  pullPolicy: Always
  replicaCount: 1
  service:
    port: 8443